[tool.poetry]
name = "iot-utils"
version = "0.1.0"
description = ""
authors = ["Thomas Kleinöder <devel@time4oss.de>"]
readme = "README.md"
packages = [{include = "iot_utils"}]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.8"
paho-mqtt = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

